// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4NsNV1xTC4KXzF1jTkyJ4OSzfSAu6jEA',
    appId: '1:702429954981:web:056d0ae11f0a8b062fde4c',
    messagingSenderId: '702429954981',
    projectId: 'group-chat-app-1d82e',
    authDomain: 'group-chat-app-1d82e.firebaseapp.com',
    storageBucket: 'group-chat-app-1d82e.appspot.com',
    measurementId: 'G-3Z0ME9MHD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsXIe6Nyep2pa6HcpD1V5Yq68B0yxYnRk',
    appId: '1:702429954981:android:40ef1d8a6a7959702fde4c',
    messagingSenderId: '702429954981',
    projectId: 'group-chat-app-1d82e',
    storageBucket: 'group-chat-app-1d82e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbrww0E1f-sdwiHCYWiZyuVdgaIjdCFWY',
    appId: '1:702429954981:ios:8607d417be0000762fde4c',
    messagingSenderId: '702429954981',
    projectId: 'group-chat-app-1d82e',
    storageBucket: 'group-chat-app-1d82e.appspot.com',
    iosBundleId: 'com.example.groupChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbrww0E1f-sdwiHCYWiZyuVdgaIjdCFWY',
    appId: '1:702429954981:ios:8607d417be0000762fde4c',
    messagingSenderId: '702429954981',
    projectId: 'group-chat-app-1d82e',
    storageBucket: 'group-chat-app-1d82e.appspot.com',
    iosBundleId: 'com.example.groupChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4NsNV1xTC4KXzF1jTkyJ4OSzfSAu6jEA',
    appId: '1:702429954981:web:abbcfca2b86dca1e2fde4c',
    messagingSenderId: '702429954981',
    projectId: 'group-chat-app-1d82e',
    authDomain: 'group-chat-app-1d82e.firebaseapp.com',
    storageBucket: 'group-chat-app-1d82e.appspot.com',
    measurementId: 'G-XHFFSXTW9X',
  );
}
